; generated by Slic3r 1.2.9 on 2016-03-10 at 20:34:43

; external perimeters extrusion width = 1.54mm
; perimeters extrusion width = 2.62mm
; infill extrusion width = 6.27mm
; solid infill extrusion width = 2.62mm
; top infill extrusion width = 2.62mm

M107
M104 S30 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M302
M92 E10000
M500
M501
G1 E100
M109 S30 ; wait for temperature to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
G1 Z0.300 F7800.000
G1 X124.189 Y124.324 F7800.000
G1 X124.189 Y117.577 E0.30528 F600.000
G1 X125.811 Y117.577 E0.37867
G1 X125.811 Y132.423 E1.05044
G1 X124.189 Y132.423 E1.12384 F600.000
G1 X124.189 Y124.555 E1.47988
G1 X125.585 Y118.007 F7800.000
G1 X125.381 Y117.803 E1.49329 F600.000
G1 X124.820 Y117.803 E1.51944
G1 X125.585 Y118.568 E1.56983
G1 X125.585 Y119.129 E1.59598
G1 X124.415 Y117.959 E1.67305
G1 X124.415 Y118.521 E1.69920
G1 X125.585 Y119.691 E1.77628
G1 X125.585 Y120.252 E1.80242
G1 X124.415 Y119.082 E1.87950
G1 X124.415 Y119.643 E1.90565
G1 X125.585 Y120.813 E1.98272
G1 X125.585 Y121.375 E2.00887
G1 X124.415 Y120.205 E2.08595
G1 X124.415 Y120.766 E2.11210
G1 X125.585 Y121.936 E2.18917
G1 X125.585 Y122.498 E2.21532
G1 X124.415 Y121.327 E2.29240
G1 X124.415 Y121.889 E2.31854
G1 X125.585 Y123.059 E2.39562
G1 X125.585 Y123.620 E2.42177
G1 X124.415 Y122.450 E2.49885
G1 X124.415 Y123.012 E2.52499
G1 X125.585 Y124.182 E2.60207
G1 X125.585 Y124.743 E2.62822
G1 X124.415 Y123.573 E2.70529
G1 X124.415 Y124.134 E2.73144
G1 X125.585 Y125.304 E2.80852
G1 X125.585 Y125.866 E2.83467
G1 X124.415 Y124.696 E2.91174
G1 X124.415 Y125.257 E2.93789
G1 X125.585 Y126.427 E3.01497
G1 X125.585 Y126.988 E3.04111
G1 X124.415 Y125.818 E3.11819
G1 X124.415 Y126.380 E3.14434
G1 X125.585 Y127.550 E3.22142
G1 X125.585 Y128.111 E3.24756
G1 X124.415 Y126.941 E3.32464
G1 X124.415 Y127.503 E3.35079
G1 X125.585 Y128.673 E3.42786
G1 X125.585 Y129.234 E3.45401
G1 X124.415 Y128.064 E3.53109
G1 X124.415 Y128.625 E3.55724
G1 X125.585 Y129.795 E3.63431
G1 X125.585 Y130.357 E3.66046
G1 X124.415 Y129.187 E3.73754
G1 X124.415 Y129.748 E3.76368
G1 X125.585 Y130.918 E3.84076
G1 X125.585 Y131.479 E3.86691
G1 X124.415 Y130.309 E3.94398
G1 X124.415 Y130.871 E3.97013
G1 X125.585 Y132.041 E4.04721
G1 X125.180 Y132.197 E4.06743
G1 X124.415 Y131.432 E4.11782
G1 X124.415 Y131.993 E4.14397
G1 X124.619 Y132.197 E4.15738
M106 S255
G92 E0
G1 Z0.600 F7800.000
G1 X125.000 Y132.648 F7800.000
G1 X125.000 Y117.352 E4.58339 F600.000
G92 E0
G1 Z0.900 F7800.000
G1 X125.000 Y132.648 F7800.000
G1 X125.000 Y117.352 E4.58339 F600.000
G92 E0
G1 Z1.200 F7800.000
G1 X125.000 Y132.648 F7800.000
G1 X125.000 Y117.352 E4.58339 F600.000
G92 E0
G1 Z1.500 F7800.000
G1 X125.000 Y132.648 F7800.000
G1 X125.000 Y117.352 E4.58339 F600.000
G92 E0
G1 Z1.800 F7800.000
G1 X125.000 Y132.648 F7800.000
G1 X125.000 Y117.352 E4.58339 F600.000
G92 E0
G1 Z2.100 F7800.000
G1 X125.000 Y132.648 F7800.000
G1 X125.000 Y117.352 E4.58339 F600.000
G92 E0
M107
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors

; filament used = 31.7mm (0.2cm3)

; avoid_crossing_perimeters = 1
; bed_shape = 0x0,250x0,250x250,0x250
; bed_temperature = 0
; before_layer_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 1
; duplicate_distance = 6
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 3
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #FFFFFF
; filament_diameter = 3.125
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 150%
; first_layer_speed = 90%
; first_layer_temperature = 30
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = reprap
; infill_acceleration = 0
; infill_first = 0
; layer_gcode = 
; max_fan_speed = 100
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 1.54
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 1
; retract_length = 0
; retract_length_toolchange = 10
; retract_lift = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 0
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slowdown_below_layer_time = 30
; spiral_vase = 0
; standby_temperature_delta = -5
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\nM302\nM92 E10000\nM500\nM501\nG1 E100
; temperature = 30
; threads = 2
; toolchange_gcode = 
; travel_speed = 130
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 0
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 100%
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.3
; raft_layers = 0
; seam_position = random
; support_material = 0
; support_material_angle = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = pillars
; support_material_spacing = 2.5
; support_material_speed = 7
; support_material_threshold = 0
; xy_size_compensation = 0
; bottom_solid_layers = 3
; bridge_flow_ratio = 1
; bridge_speed = 10
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 70%
; external_perimeters_first = 1
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 60%
; fill_pattern = rectilinear
; gap_fill_speed = 10
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_overlap = 15%
; infill_speed = 10
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 10
; perimeters = 1
; small_perimeter_speed = 70%
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 10
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 10
; top_solid_layers = 3
