; generated by Slic3r 1.2.9 on 2016-03-10 at 20:37:08

; external perimeters extrusion width = 1.54mm
; perimeters extrusion width = 2.62mm
; infill extrusion width = 6.27mm
; solid infill extrusion width = 2.62mm
; top infill extrusion width = 2.62mm

M107
M104 S30 ; set temperature
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M302
M92 E10000
M500
M501
G1 E100
M109 S30 ; wait for temperature to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
G1 Z0.300 F7800.000
G1 X129.663 Y130.867 F7800.000
G1 X126.131 Y121.800 E0.44029 F600.000
G1 X125.209 Y119.056 E0.57130
G1 X124.813 Y119.056 E0.58918
G1 X123.890 Y121.800 E0.72020
G1 X119.730 Y132.423 E1.23642
G1 X118.039 Y132.423 E1.31294
G1 X124.078 Y117.577 E2.03816
G1 X125.923 Y117.577 E2.12161
G1 X131.620 Y131.586 E2.80591
G1 X131.961 Y132.423 E2.84681 F600.000
G1 X130.269 Y132.423 E2.92337
G1 X129.746 Y131.082 E2.98848
G1 X129.971 Y130.939 F7800.000
G1 X131.229 Y132.197 E3.06933 F600.000
G1 X131.454 Y131.874 E3.08722
G1 X129.622 Y130.042 E3.20499
G1 X129.272 Y129.145 F7800.000
G1 X131.078 Y130.951 E3.32109 F600.000
G1 X130.702 Y130.027 F7800.000
G1 X128.922 Y128.247 E3.43552 F600.000
G1 X128.573 Y127.350 F7800.000
G1 X130.327 Y129.104 E3.54829 F600.000
G1 X129.951 Y128.180 F7800.000
G1 X128.223 Y126.452 E3.65939 F600.000
G1 X127.874 Y125.555 F7800.000
G1 X129.576 Y127.257 E3.76883 F600.000
G1 X129.200 Y126.334 F7800.000
G1 X127.524 Y124.657 E3.87660 F600.000
G1 X128.449 Y124.487 F7800.000
G1 X126.825 Y122.862 E3.98103 F600.000
G1 X127.698 Y122.640 F7800.000
G1 X126.170 Y121.111 E4.07929 F600.000
G1 X126.947 Y120.793 F7800.000
G1 X125.615 Y119.461 E4.16490 F600.000
G1 X126.196 Y118.946 F7800.000
G1 X125.052 Y117.803 E4.23840 F600.000
G1 X125.600 Y117.803 E4.26331
G1 X125.820 Y118.023 E4.27745
G1 X124.984 Y118.830 F7800.000
G1 X124.132 Y117.978 E4.33217 F600.000
G1 X124.505 Y117.803 E4.35089
G1 X126.571 Y119.870 E4.48375
G1 X125.892 Y120.286 F7800.000
G1 X127.323 Y121.717 E4.57569 F600.000
G1 X126.475 Y121.965 F7800.000
G1 X128.074 Y123.563 E4.67845 F600.000
G1 X127.174 Y123.760 F7800.000
G1 X128.825 Y125.410 E4.78455 F600.000
G1 X130.321 Y131.837 F7800.000
G1 X130.681 Y132.197 E4.80770 F600.000
G92 E0
G1 X119.469 Y130.965 F7800.000
G1 X119.469 Y130.965 F7800.000
G1 X119.198 Y131.643 F7800.000
G1 X119.191 Y131.648 F7800.000
G1 X118.628 Y132.197 F7800.000
G1 X118.429 Y131.998 E0.01279 F600.000
G1 X118.588 Y131.609 E0.03190
G1 X119.176 Y132.197 E0.06972
G1 X119.637 Y132.110 E0.09102
G1 X118.746 Y131.219 E0.14826
G1 X118.905 Y130.830 E0.16737
G1 X119.791 Y131.716 E0.22433
G1 X119.945 Y131.322 E0.24355
G1 X119.063 Y130.440 E0.30024
G1 X119.221 Y130.051 E0.31935
G1 X120.099 Y130.929 E0.37576
G1 X120.253 Y130.535 E0.39498
G1 X119.380 Y129.662 E0.45112
G1 X119.538 Y129.272 E0.47023
G1 X120.407 Y130.141 E0.52610
G1 X120.562 Y129.747 E0.54532
G1 X119.697 Y128.883 E0.60092
G1 X119.855 Y128.493 E0.62003
G1 X120.716 Y129.354 E0.67535
G1 X120.870 Y128.960 E0.69457
G1 X120.014 Y128.104 E0.74962
G1 X120.172 Y127.714 E0.76874
G1 X121.024 Y128.566 E0.82351
G1 X121.178 Y128.173 E0.84273
G1 X120.330 Y127.325 E0.89724
G1 X120.489 Y126.935 E0.91635
G1 X121.332 Y127.779 E0.97058
G1 X121.487 Y127.385 E0.98980
G1 X120.647 Y126.546 E1.04376
G1 X120.806 Y126.157 E1.06287
G1 X121.641 Y126.992 E1.11656
G1 X121.795 Y126.598 E1.13578
G1 X120.964 Y125.767 E1.18919
G1 X121.122 Y125.378 E1.20830
G1 X121.949 Y126.204 E1.26144
G1 X122.103 Y125.811 E1.28066
G1 X121.281 Y124.988 E1.33353
G1 X121.439 Y124.599 E1.35264
G1 X122.257 Y125.417 E1.40523
G1 X122.412 Y125.023 E1.42445
G1 X121.598 Y124.209 E1.47678
G1 X121.756 Y123.820 E1.49589
G1 X122.566 Y124.630 E1.54794
G1 X122.720 Y124.236 E1.56715
G1 X121.914 Y123.431 E1.61893
G1 X122.073 Y123.041 E1.63804
G1 X122.874 Y123.842 E1.68955
G1 X123.028 Y123.449 E1.70876
G1 X122.231 Y122.652 E1.75999
G1 X122.390 Y122.262 E1.77911
G1 X123.182 Y123.055 E1.83006
G1 X123.337 Y122.661 E1.84928
G1 X122.548 Y121.873 E1.89997
G1 X122.707 Y121.483 E1.91908
G1 X123.491 Y122.268 E1.96949
G1 X123.645 Y121.874 E1.98871
G1 X122.865 Y121.094 E2.03885
G1 X123.023 Y120.705 E2.05796
G1 X123.787 Y121.468 E2.10704
G1 X123.925 Y121.058 E2.12670
G1 X123.182 Y120.315 E2.17446
G1 X123.340 Y119.926 E2.19357
G1 X124.063 Y120.648 E2.24000
G1 X124.200 Y120.238 E2.25967
G1 X123.499 Y119.536 E2.30478
G1 X123.657 Y119.147 E2.32389
G1 X124.338 Y119.828 E2.36769
G1 X124.476 Y119.418 E2.38735
G1 X123.815 Y118.757 E2.42983
G1 X123.974 Y118.368 E2.44894
G1 X124.614 Y119.008 E2.49009
M106 S255
G92 E0
G1 Z0.600 F7800.000
G1 X131.202 Y132.648 F7800.000
G1 X126.788 Y121.562 E3.57549 F600.000
G1 X125.843 Y119.013 E4.39000
G1 X125.403 Y118.349 E4.62869
G1 X124.975 Y118.316 E4.75724
G1 X124.600 Y118.353 E4.87012
G1 X124.170 Y119.010 E5.10552
G1 X123.224 Y121.558 E5.91986
G1 X118.797 Y132.648 E9.49798
G92 E0
G1 Z0.900 F7800.000
G1 X131.202 Y132.648 F7800.000
G1 X126.788 Y121.562 E3.57549 F600.000
G1 X125.843 Y119.013 E4.39000
G1 X125.403 Y118.349 E4.62869
G1 X124.975 Y118.316 E4.75724
G1 X124.600 Y118.353 E4.87012
G1 X124.170 Y119.010 E5.10552
G1 X123.224 Y121.558 E5.91986
G1 X118.797 Y132.648 E9.49798
G92 E0
G1 Z1.200 F7800.000
G1 X131.202 Y132.648 F7800.000
G1 X126.788 Y121.562 E3.57549 F600.000
G1 X125.843 Y119.013 E4.39000
G1 X125.403 Y118.349 E4.62869
G1 X124.975 Y118.316 E4.75724
G1 X124.600 Y118.353 E4.87012
G1 X124.170 Y119.010 E5.10552
G1 X123.224 Y121.558 E5.91986
G1 X118.797 Y132.648 E9.49798
G92 E0
G1 Z1.500 F7800.000
G1 X131.202 Y132.648 F7800.000
G1 X126.788 Y121.562 E3.57549 F600.000
G1 X125.843 Y119.013 E4.39000
G1 X125.403 Y118.349 E4.62869
G1 X124.975 Y118.316 E4.75724
G1 X124.600 Y118.353 E4.87012
G1 X124.170 Y119.010 E5.10552
G1 X123.224 Y121.558 E5.91986
G1 X118.797 Y132.648 E9.49798
G92 E0
G1 Z1.800 F7800.000
G1 X131.202 Y132.648 F7800.000
G1 X126.788 Y121.562 E3.57549 F600.000
G1 X125.843 Y119.013 E4.39000
G1 X125.403 Y118.349 E4.62869
G1 X124.975 Y118.316 E4.75724
G1 X124.600 Y118.353 E4.87012
G1 X124.170 Y119.010 E5.10552
G1 X123.224 Y121.558 E5.91986
G1 X118.797 Y132.648 E9.49798
G92 E0
G1 Z2.100 F7800.000
G1 X131.202 Y132.648 F7800.000
G1 X126.788 Y121.562 E3.57549 F600.000
G1 X125.843 Y119.013 E4.39000
G1 X125.403 Y118.349 E4.62869
G1 X124.975 Y118.316 E4.75724
G1 X124.600 Y118.353 E4.87012
G1 X124.170 Y119.010 E5.10552
G1 X123.224 Y121.558 E5.91986
G1 X118.797 Y132.648 E9.49798
G92 E0
M107
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors

; filament used = 64.3mm (0.5cm3)

; avoid_crossing_perimeters = 1
; bed_shape = 0x0,250x0,250x250,0x250
; bed_temperature = 0
; before_layer_gcode = 
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 1
; duplicate_distance = 6
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 3
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #FFFFFF
; filament_diameter = 3.125
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 150%
; first_layer_speed = 90%
; first_layer_temperature = 30
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = reprap
; infill_acceleration = 0
; infill_first = 0
; layer_gcode = 
; max_fan_speed = 100
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 1.54
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = 
; pressure_advance = 0
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 1
; retract_length = 0
; retract_length_toolchange = 10
; retract_lift = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 0
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slowdown_below_layer_time = 30
; spiral_vase = 0
; standby_temperature_delta = -5
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\nM302\nM92 E10000\nM500\nM501\nG1 E100
; temperature = 30
; threads = 2
; toolchange_gcode = 
; travel_speed = 130
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 0
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 100%
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.3
; raft_layers = 0
; seam_position = random
; support_material = 0
; support_material_angle = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = pillars
; support_material_spacing = 2.5
; support_material_speed = 7
; support_material_threshold = 0
; xy_size_compensation = 0
; bottom_solid_layers = 3
; bridge_flow_ratio = 1
; bridge_speed = 10
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 70%
; external_perimeters_first = 1
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 60%
; fill_pattern = rectilinear
; gap_fill_speed = 10
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_overlap = 15%
; infill_speed = 10
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 10
; perimeters = 1
; small_perimeter_speed = 70%
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 10
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 10
; top_solid_layers = 3
